# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb18e2fce99a9a1782ffcbfc69392f620b19eea71a6700f6253a04ac49b283558f24bd76ba98d27b4c254bb1eefc3783d2c56726e6d52dd4da68c17f6ea6c96f

test:
  secret_key_base: 52c6e651fd6f19ede4566fcddebe182865b5699a701676bb5790effdfde5502444aa7dab0e4ad8d9698ef12feda85d1eca5eb348c802847c9e8367cced9a59dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
